name: Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - name: Install Linux Webkit deps
        run: npx playwright install-deps webkit
      - name: Cypress Chrome
        uses: cypress-io/github-action@v5
        with:
          install: false
          component: true
          browser: chrome
      - name: Cypress Firefox
        uses: cypress-io/github-action@v5
        with:
          install: false
          component: true
          browser: firefox
      - name: Cypress Webkit
        uses: cypress-io/github-action@v5
        with:
          install: false
          component: true
          browser: webkit
